Threshold = 78
DisplayMonitorSources = false
EnableUpdates = true
FilterInput = true
FilterOutput = false
LastUsedInput = "alsa_input.usb-ARTURIA_MiniFuse_1_8831400345061105-00.Direct__hw_M1__source"
LastUsedOutput = ""
