format = """
$username@\
$hostname\
$directory\
$time\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$docker_context\
$memory_usage\
$git_branch\
$git_status\
$line_break\
$character\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
format = '[\[ ](bold 207)[$user]($style)'

[directory]
format = " [$path](177)"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[:❯](green)"
error_symbol = "[ ╯°□°╯︵ ┻━┻](red)"
vimcmd_symbol = "[Vi ](bold green)"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
format = '[ $symbol ($version)]($style)'

[docker_context]
symbol = " "
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
format = '[ $symbol ($version)]($style)'

[elm]
symbol = " "
format = '[ $symbol ($version)]($style)'

[git_branch]
symbol = ""
format = '[ $symbol $branch ]($style)'

[git_status]
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
format = '[ $symbol ($version)]($style)'

[haskell]
symbol = " "
format = '[ $symbol ($version)]($style)'

[java]
symbol = " "
format = '[ $symbol ($version)]($style)'

[julia]
symbol = " "
format = '[ $symbol ($version)]($style)'

[nodejs]
symbol = ""
version_format = '$major'
format = '[ $symbol ($version)]($style)'

[nim]
symbol = " "
format = '[ $symbol ($version)]($style)'

[rust]
symbol = ""
format = '[ $symbol ($version)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[ ♥ $time ](7)[\]](bold 207) [:: ILYL](243)'

[hostname]
ssh_only = false
ssh_symbol = ' \[remote\] '
format = "[$hostname](bold red)[$ssh_symbol](green)"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = false
threshold = 70
symbol = ""
style = "bold cyan"
format = "$symbol[${ram}( ${swap})]($style) " 

